# Generated by Django 4.2.17 on 2025-02-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('service_type', models.CharField(choices=[('web_dev', 'Web Development'), ('app_dev', 'App Development'), ('ai', 'AI Services'), ('machine learning', 'Machine Learning'), ('data_science', 'Data Science'), ('other', 'Other')], default='other', max_length=50)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
